export interface User {
  id: string
  email: string
  name?: string
  avatar?: string
  role: 'user' | 'admin'
  level: number
  xp: number
}

export interface Language {
  id: string
  code: string
  name: string
  flagUrl?: string
}

export interface Course {
  id: string
  languageId: string
  level: string
  name: string
  description?: string
  orderIndex: number
}

export interface Theme {
  id: string
  courseId: string
  name: string
  description?: string
  orderIndex: number
}

export interface Lesson {
  id: string
  themeId: string
  name: string
  description?: string
  slides: Slide[]
  orderIndex: number
  estimatedDuration?: number
}

export interface Slide {
  id: string
  type: 'theory' | 'quiz_single' | 'quiz_multiple' | 'fill_gap' | 'match'
  content: SlideContent
  feedback?: string
}

export interface SlideContent {
  title?: string
  text?: string
  image?: string
  question?: string
  options?: string[]
  correctAnswers?: number[]
  gaps?: GapItem[]
  matchPairs?: MatchPair[]
}

export interface GapItem {
  text: string
  isGap: boolean
  correctAnswer?: string
}

export interface MatchPair {
  left: string
  right: string
}

export interface LessonProgress {
  id: string
  userId: string
  lessonId: string
  currentSlide: number
  completed: boolean
  score?: number
  timeSpent?: number
  startedAt: Date
  completedAt?: Date
}

export interface Vocabulary {
  id: string
  languageId: string
  word: string
  transcription?: string
  translation: string
  partOfSpeech?: string
  audioUrl?: string
  exampleSentence?: string
}

export interface FlashcardSet {
  id: string
  userId: string
  name: string
  description?: string
  autoGenerated: boolean
  sourceLessonId?: string
  createdAt: Date
}

export interface Flashcard {
  id: string
  setId: string
  vocabularyId: string
  vocabulary?: Vocabulary
  easeFactor: number
  intervalDays: number
  repetitions: number
  nextReview: Date
}

export type SRSRating = 1 | 2 | 3 | 4 // Again, Hard, Good, Easy

export interface Achievement {
  id: string
  name: string
  description: string
  iconUrl?: string
  type: 'streak' | 'explorer' | 'sprinter' | 'consistent'
  conditionData: Record<string, any>
  xpReward: number
}

export interface UserAchievement {
  id: string
  userId: string
  achievementId: string
  achievement?: Achievement
  earnedAt: Date
}

export interface SlideAnswer {
  slideId: string
  answer: any
  isCorrect: boolean
  timeSpent: number
}

export interface StudyResults {
  totalCards: number
  correctAnswers: number
  timeSpent: number
  accuracy: number
}